"""Advanced Sprint Features

Revision ID: 09a44fc701e4
Revises: 09bbd2a51388
Create Date: 2026-09-02 20:23:18.244685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a44fc701e4'
down_revision: Union[str, Sequence[str], None] = '09bbd2a51388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SprintStatus.ARCHIVED if not exists
    op.execute("ALTER TYPE sprintstatus ADD VALUE IF NOT EXISTS 'ARCHIVED'")
    
    # Add new AuditActions
    op.execute("ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'SPRINT_EXTENDED'")
    op.execute("ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'SPRINT_ARCHIVED'")
    op.execute("ALTER TYPE auditaction ADD VALUE IF NOT EXISTS 'SPRINT_DELETED'")

    # Add columns
    op.add_column('issues', sa.Column('estimated_effort', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('goal_status', sa.String(length=50), server_default='NOT_STARTED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'goal_status')
    op.drop_column('issues', 'estimated_effort')
    # ### end Alembic commands ###
