"""Add advanced sprint fields

Revision ID: 09bbd2a51388
Revises: 28cff28bf305
Create Date: 2026-09-02 19:57:06.684904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bbd2a51388'
down_revision: Union[str, Sequence[str], None] = '28cff28bf305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sprints', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sprints', sa.Column('estimated_team_members', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('working_days', sa.Integer(), nullable=True))
    op.add_column('sprints', sa.Column('hours_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'hours_per_day')
    op.drop_column('sprints', 'working_days')
    op.drop_column('sprints', 'estimated_team_members')
    op.drop_column('sprints', 'completed_at')
    op.drop_column('sprints', 'actual_start_date')
    # ### end Alembic commands ###
