"""add issue detail and resolution columns

Revision ID: 24aecb9465fc
Revises: dda1ef4bc731
Create Date: 2026-08-25 00:26:54.860537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24aecb9465fc'
down_revision: Union[str, Sequence[str], None] = 'dda1ef4bc731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('environment', sa.String(length=200), nullable=True))
    op.add_column('issues', sa.Column('steps_to_reproduce', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('expected_result', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('actual_result', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('resolution_summary', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'resolved_at')
    op.drop_column('issues', 'resolution_summary')
    op.drop_column('issues', 'actual_result')
    op.drop_column('issues', 'expected_result')
    op.drop_column('issues', 'steps_to_reproduce')
    op.drop_column('issues', 'environment')
    # ### end Alembic commands ###
