"""add audit logs

Revision ID: e3be5018d5be
Revises: 24aecb9465fc
Create Date: 2026-08-25 16:23:25.654612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3be5018d5be'
down_revision: Union[str, Sequence[str], None] = '24aecb9465fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('ISSUE_CREATED', 'ISSUE_UPDATED', 'ISSUE_ASSIGNED', 'ISSUE_STATUS_CHANGED', 'ISSUE_RESOLVED', 'ISSUE_REOPENED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DEACTIVATED', 'AUTH_LOGIN', 'AUTH_LOGOUT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='ISSUE | PROJECT | AUTH'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='Integer ID of the affected resource, if applicable.'),
    sa.Column('entity_key', sa.String(length=100), nullable=True, comment='Human-readable key, e.g. DM-0001 or AGRO.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable sentence describing the action.'),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Previous field values (changed fields only).'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='New field values (changed fields only).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at_desc', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_key'), 'audit_logs', ['entity_key'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_entity_type_action', 'audit_logs', ['entity_type', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_key'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
