import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type {
  DeveloperAnalyticsItem,
  IssueStatusDistributionResponse,
  ProjectAnalyticsResponse,
  SeverityDistributionResponse,
  PriorityDistributionResponse,
  IssueTrendResponse,
  SystemAnalyticsResponse,
} from '../types/analytics';
import type { Comment } from '../types/comment';
import type { Issue, IssueDetail } from '../types/issue';
import type { Project } from '../types/project';
import { formatDate } from './formatters';

interface UserInfo {
  full_name?: string;
  email?: string;
  role?: string;
}

interface AnalyticsReportData {
  user: UserInfo | null;
  statusDist: IssueStatusDistributionResponse | null;
  severityDist: SeverityDistributionResponse | null;
  projectAnalytics: ProjectAnalyticsResponse[];
  devAnalytics?: DeveloperAnalyticsItem[];
  systemOverview?: SystemAnalyticsResponse | null;
  priorityDist?: PriorityDistributionResponse | null;
  trends?: IssueTrendResponse | null;
  periodLabel?: string;
  generatedAt?: string;
}

/**
 * 1. Analytics & Defect Report (Matching screenshot layout)
 */
export const generateAnalyticsPdfReport = (data: AnalyticsReportData) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const currentDate = data.generatedAt || new Date().toLocaleString();

  // Primary Dark Navy Banner
  doc.setFillColor(15, 23, 42); // #0f172a
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('BUGTRACKER — ANALYTICS & DEFECT REPORT', 14, 14);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // #94a3b8
  doc.text('Intelligent Defect Lifecycle Management & Quality Assurance', 14, 21);

  // Metadata box
  let yPos = 36;
  doc.setFillColor(241, 245, 249); // #f1f5f9
  doc.roundedRect(14, yPos, pageWidth - 28, 18, 2, 2, 'F');

  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85); // #334155

  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', 18, yPos + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.user?.full_name || 'User'} (${data.user?.email || 'N/A'}) [Role: ${data.user?.role || 'USER'}]`, 42, yPos + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Report Date:', 18, yPos + 12);
  doc.setFont('helvetica', 'normal');
  doc.text(currentDate, 42, yPos + 12);

  if (data.periodLabel) {
    doc.setFont('helvetica', 'bold');
    doc.text('Period:', 18, yPos + 18);
    doc.setFont('helvetica', 'normal');
    doc.text(data.periodLabel, 42, yPos + 18);
  }

  const validProjects = data.periodLabel 
    ? (data.projectAnalytics || [])
    : (data.projectAnalytics || []).filter(
        (p) => p.total_issues > 0 || ['CORE', 'MOB', 'API'].includes(p.project_key)
      );
  const activeCount = validProjects.length > 0 ? validProjects.length : data.projectAnalytics.length;

  doc.setFont('helvetica', 'bold');
  doc.text('Active Projects:', 130, yPos + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(`${activeCount} Projects Tracked`, 156, yPos + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Status:', 130, yPos + 12);
  doc.setFont('helvetica', 'normal');
  doc.text('Official QA Summary', 156, yPos + 12);

  yPos += 26;

  // 1. Defect Status & Severity Distribution
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('1. Defect Status & Severity Distribution', 14, yPos);
  yPos += 4;

  const totalStatus = data.statusDist
    ? Object.values(data.statusDist).reduce((a, b) => a + b, 0)
    : 0;

  const statusRows = [
    [
      'Reported / Triaged',
      String((data.statusDist?.REPORTED || 0) + (data.statusDist?.TRIAGED || 0)),
      'Blocker',
      String(data.severityDist?.BLOCKER || 0),
    ],
    [
      'Assigned to Tester',
      String(data.statusDist?.ASSIGNED || 0),
      'Critical',
      String(data.severityDist?.CRITICAL || 0),
    ],
    [
      'In Investigation / Review',
      String(
        (data.statusDist?.IN_DEVELOPMENT || 0) +
        (data.statusDist?.IN_REVIEW || 0) +
        (data.statusDist?.IN_TESTING || 0)
      ),
      'Major',
      String(data.severityDist?.MAJOR || 0),
    ],
    [
      'Resolved by Tester',
      String(data.statusDist?.RESOLVED || 0),
      'Minor',
      String(data.severityDist?.MINOR || 0),
    ],
    [
      'Confirmed Closed',
      String(data.statusDist?.CLOSED || 0),
      'Total Defects',
      String(totalStatus),
    ],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Status Category', 'Count', 'Severity Level', 'Count']],
    body: statusRows,
    theme: 'grid',
    headStyles: {
      fillColor: [99, 102, 241], // #6366f1
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    styles: {
      fontSize: 8.5,
      cellPadding: 2.8,
      lineColor: [226, 232, 240],
      lineWidth: 0.15,
      textColor: [51, 65, 85],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 55 },
      1: { halign: 'center', cellWidth: 35 },
      2: { fontStyle: 'bold', cellWidth: 55 },
      3: { halign: 'center', cellWidth: 37 },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // 2. Priority Distribution & Trend Summary
  if (data.priorityDist || data.trends) {
    if (yPos > pageHeight - 65) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('2. Priority Distribution & Trend Summary', 14, yPos);
    yPos += 4;

    const summaryRows = [
      ['Urgent Priority', String(data.priorityDist?.URGENT || 0), 'Total Created (Trend)', String(data.trends?.total_created || 0)],
      ['High Priority', String(data.priorityDist?.HIGH || 0), 'Total Resolved (Trend)', String(data.trends?.total_resolved || 0)],
      ['Medium Priority', String(data.priorityDist?.MEDIUM || 0), 'Trend Interval', data.trends?.interval || '-'],
      ['Low Priority', String(data.priorityDist?.LOW || 0), 'Data Points Recorded', String(data.trends?.items.length || 0)],
    ];

    autoTable(doc, {
      startY: yPos,
      head: [['Priority Level', 'Count', 'Trend Metric', 'Value']],
      body: summaryRows,
      theme: 'grid',
      headStyles: {
        fillColor: [99, 102, 241],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      styles: { fontSize: 8.5, cellPadding: 2.8, lineColor: [226, 232, 240], lineWidth: 0.15, textColor: [51, 65, 85] },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 55 },
        1: { halign: 'center', cellWidth: 35 },
        2: { fontStyle: 'bold', cellWidth: 55 },
        3: { halign: 'center', cellWidth: 37 },
      },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  // 3. Project Performance & Resolution Rates
  if (yPos > pageHeight - 65) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('3. Project Performance & Resolution Rates', 14, yPos);
  yPos += 4;

  const projectRows = (validProjects.length > 0 ? validProjects : data.projectAnalytics).map((proj) => [
    proj.project_key,
    proj.project_name,
    String(proj.total_issues),
    String(proj.open_issues),
    String(proj.in_progress_issues),
    String(proj.resolved_issues),
    String(proj.closed_issues),
    `${proj.resolution_rate.toFixed(1)}%`,
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [['Key', 'Project Name', 'Total', 'Open', 'In Progress', 'Resolved', 'Closed', 'Resolution Rate']],
    body: projectRows.length > 0 ? projectRows : [['-', 'No project records found', '0', '0', '0', '0', '0', '0.0%']],
    theme: 'striped',
    headStyles: {
      fillColor: [30, 41, 59], // #1e293b
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.8,
      lineColor: [241, 245, 249],
      lineWidth: 0.1,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 16 },
      1: { cellWidth: 58 },
      2: { halign: 'center', cellWidth: 14 },
      3: { halign: 'center', cellWidth: 14 },
      4: { halign: 'center', cellWidth: 22 },
      5: { halign: 'center', cellWidth: 18 },
      6: { halign: 'center', cellWidth: 16 },
      7: { halign: 'center', cellWidth: 24, fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // 4. Tester / Developer Productivity (If present)
  if (data.devAnalytics && data.devAnalytics.length > 0) {
    if (yPos > pageHeight - 50) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('4. Tester & Developer Productivity', 14, yPos);
    yPos += 4;

    const devRows = data.devAnalytics.map((dev) => [
      dev.developer_name,
      dev.developer_email,
      String(dev.assigned_issues),
      String(dev.resolved_issues),
      String(dev.open_issues),
      `${dev.resolution_rate.toFixed(1)}%`,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Member Name', 'Email', 'Assigned', 'Resolved', 'Open', 'Resolution Rate']],
      body: devRows,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8.5 },
      styles: { fontSize: 8, cellPadding: 2.5 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        1: { cellWidth: 65 },
        2: { halign: 'center', cellWidth: 20 },
        3: { halign: 'center', cellWidth: 20 },
        4: { halign: 'center', cellWidth: 20 },
        5: { halign: 'center', cellWidth: 25, fontStyle: 'bold' },
      },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'BugTracker Enterprise • Confidential Quality Assurance Report • Generated from PostgreSQL Engine',
      14,
      pageHeight - 8
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 25, pageHeight - 8);
  }

  let pLabel = data.periodLabel ? data.periodLabel.replace(/\s+/g, '') : 'Generated';
  const filename = `BugTracker_${pLabel}_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};

/**
 * 2. Issues & Defect Registry PDF Report (Landscape)
 */
export const generateIssuesPdfReport = (
  issues: Issue[],
  currentUser: UserInfo | null,
  filterSummary?: string,
  projectsList?: Project[]
) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const currentDate = new Date().toLocaleString();

  const projMap = new Map<number, string>();
  if (projectsList) {
    projectsList.forEach((p) => projMap.set(p.id, `${p.project_key} — ${p.name}`));
  }

  // Top Dark Header Banner
  doc.setFillColor(15, 23, 42); // #0f172a
  doc.rect(0, 0, pageWidth, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('BUGTRACKER — DEFECT & ISSUE REGISTRY REPORT', 14, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Total Issues: ${issues.length} | Generated: ${currentDate} | Requester: ${currentUser?.full_name || 'User'} (${currentUser?.role || 'USER'}) ${
      filterSummary ? `| ${filterSummary}` : ''
    }`,
    14,
    18
  );

  const totalCount = issues.length;
  const openCount = issues.filter((i) => !['RESOLVED', 'CLOSED'].includes(i.status)).length;
  const inProgressCount = issues.filter((i) => ['IN_DEVELOPMENT', 'IN_REVIEW', 'IN_TESTING'].includes(i.status)).length;
  const resolvedCount = issues.filter((i) => i.status === 'RESOLVED').length;
  const closedCount = issues.filter((i) => i.status === 'CLOSED').length;
  const criticalCount = issues.filter((i) => ['BLOCKER', 'CRITICAL'].includes(i.severity)).length;
  const resolutionRate = totalCount > 0 ? Math.round(((resolvedCount + closedCount) / totalCount) * 100) : 0;

  let yPos = 28;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, yPos, pageWidth - 28, 9, 1, 1, 'FD');

  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Overview: Total: ${totalCount} | Open: ${openCount} | In Progress: ${inProgressCount} | Resolved: ${resolvedCount} | Closed: ${closedCount} | Critical/Blocker: ${criticalCount} | Resolution Rate: ${resolutionRate}%`,
    18,
    yPos + 6
  );

  yPos += 13;

  const issueRows = issues.map((iss) => {
    const projLabel = projMap.get(iss.project_id) || `Project #${iss.project_id}`;
    return [
      iss.issue_key,
      iss.title,
      projLabel,
      iss.issue_type,
      iss.severity,
      iss.priority,
      iss.status,
      iss.assignee_id ? `Tester #${iss.assignee_id}` : 'Unassigned',
      formatDate(iss.created_at),
    ];
  });

  autoTable(doc, {
    startY: yPos,
    head: [['Key', 'Defect Title', 'Project', 'Type', 'Severity', 'Priority', 'Status', 'Assignee', 'Created']],
    body: issueRows.length > 0 ? issueRows : [['-', 'No issues found matching criteria', '-', '-', '-', '-', '-', '-', '-']],
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 7.5, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 24 },
      1: { cellWidth: 80 },
      2: { cellWidth: 42 },
      3: { cellWidth: 22 },
      4: { cellWidth: 20 },
      5: { cellWidth: 20 },
      6: { cellWidth: 26, fontStyle: 'bold' },
      7: { cellWidth: 28 },
      8: { cellWidth: 24 },
    },
    margin: { left: 14, right: 14 },
  });

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text('BugTracker Enterprise • Confidential Quality Assurance Registry Report', 14, pageHeight - 6);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 25, pageHeight - 6);
  }

  const filename = `BugTracker_Issues_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};

/**
 * 3. Single Defect Audit Sheet PDF Report (Portrait)
 */
export const generateSingleIssuePdfReport = (issue: IssueDetail, comments?: Comment[]) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const currentDate = new Date().toLocaleString();

  // Header Banner
  doc.setFillColor(15, 23, 42); // #0f172a
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(`DEFECT AUDIT REPORT: ${issue.issue_key}`, 14, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Project: ${issue.project.project_key} — ${issue.project.name} | Generated: ${currentDate}`, 14, 21);

  let yPos = 36;

  // Defect Attribute Metadata Grid
  const metaRows = [
    ['Defect Title', issue.title],
    ['Current Status', issue.status],
    ['Severity / Priority', `${issue.severity} / ${issue.priority}`],
    ['Issue Type', issue.issue_type],
    ['Target Environment', issue.environment || 'Not specified (Default/Production)'],
    ['Reported By', `${issue.reporter.full_name} (${issue.reporter.email}) on ${formatDate(issue.created_at)}`],
    ['Assigned Tester', issue.assignee ? `${issue.assignee.full_name} (${issue.assignee.email})` : 'Unassigned / Awaiting Triage'],
    ['Last Updated', formatDate(issue.updated_at)],
  ];

  if (issue.resolved_at) {
    metaRows.push(['Resolved Date', formatDate(issue.resolved_at)]);
  }

  autoTable(doc, {
    startY: yPos,
    head: [['Attribute', 'Specification Details']],
    body: metaRows,
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    styles: { fontSize: 8.5, cellPadding: 2.8, lineColor: [226, 232, 240], lineWidth: 0.15 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 45 },
      1: { cellWidth: 135 },
    },
    margin: { left: 14, right: 14 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 8;

  // Section: Defect Description
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Defect Description', 14, yPos);
  yPos += 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const splitDesc = doc.splitTextToSize(issue.description || 'No description provided.', pageWidth - 28);
  doc.text(splitDesc, 14, yPos);
  yPos += splitDesc.length * 4.5 + 4;

  // Section: Steps to Reproduce
  if (issue.steps_to_reproduce) {
    if (yPos > pageHeight - 50) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text('Steps to Reproduce', 14, yPos);
    yPos += 4;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    const splitSteps = doc.splitTextToSize(issue.steps_to_reproduce, pageWidth - 28);
    doc.text(splitSteps, 14, yPos);
    yPos += splitSteps.length * 4.5 + 4;
  }

  // Section: Expected vs Actual Result
  if (issue.expected_result || issue.actual_result) {
    if (yPos > pageHeight - 50) {
      doc.addPage();
      yPos = 20;
    }
    const resultRows = [];
    if (issue.expected_result) resultRows.push(['Expected Outcome', issue.expected_result]);
    if (issue.actual_result) resultRows.push(['Actual Observed Outcome', issue.actual_result]);

    autoTable(doc, {
      startY: yPos,
      body: resultRows,
      theme: 'grid',
      styles: { fontSize: 8.5, cellPadding: 2.8, lineColor: [226, 232, 240], lineWidth: 0.15 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 45 },
        1: { cellWidth: 135 },
      },
      margin: { left: 14, right: 14 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 8;
  }

  // Section: Resolution Summary
  if (issue.resolution_summary) {
    if (yPos > pageHeight - 50) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(16, 185, 129); // Green
    doc.text('Tester Resolution Summary', 14, yPos);
    yPos += 4;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    const splitRes = doc.splitTextToSize(issue.resolution_summary, pageWidth - 28);
    doc.text(splitRes, 14, yPos);
    yPos += splitRes.length * 4.5 + 4;
  }

  // Section: Discussion & Comments
  if (comments && comments.length > 0) {
    if (yPos > pageHeight - 50) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(`Discussion & Activity Trail (${comments.length} Comments)`, 14, yPos);
    yPos += 4;

    const commentRows = comments.map((c) => [
      `${c.author?.full_name || 'Member'} (${formatDate(c.created_at)})`,
      c.body,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Author & Timestamp', 'Comment Note']],
      body: commentRows,
      theme: 'striped',
      headStyles: { fillColor: [71, 85, 105], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8.5 },
      styles: { fontSize: 8, cellPadding: 2.5 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 55 },
        1: { cellWidth: 125 },
      },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text('BugTracker Enterprise • Single Defect Audit Report • Generated from PostgreSQL Engine', 14, pageHeight - 8);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 25, pageHeight - 8);
  }

  const filename = `${issue.issue_key}_Defect_Audit_Report.pdf`;
  doc.save(filename);
};
